application/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from application import db,login_manager
from datetime import datetime,timedelta
from flask_login import UserMixin, login_user, LoginManager, login_required, logout_user, current_user
import jwt
from application.utils import read_json
from application.secret_filepaths import APP_INFO_SECRETS_PATH

app_info=read_json(APP_INFO_SECRETS_PATH)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(20), nullable=False)    
    username = db.Column(db.String(20), unique=True, nullable=False)
    dob=db.Column(db.DateTime, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    created_at=db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    last_modified_at=db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    num_modifications = db.Column(db.Integer, default=0)

    activity_id = db.relationship('Leisure_journal', backref='person')

    @property
    def password_hash(self):
        raise AttributeError('password is not a readable attribute!')
    
    @password_hash.setter
    def password_hash(self, user_entered_password):
        self.password_hash = generate_password_hash(user_entered_password)

    def verify_password(self, user_entered_password):
        return check_password_hash(self.password_hash, user_entered_password)
    
    def get_reset_paswd_token(self, expiration_time=datetime.utcnow()+timedelta(minutes=10)):
        payload={"user_id":self.id,"exp":expiration_time}
        token= jwt.encode(payload, app_info['secret_key'], algorithm="HS256")
        return token

    @staticmethod
    def verify_reset_token(token):        
        try:
            s = jwt.decode(token,app_info['secret_key'],algorithms=["HS256"])
            user_id = s['user_id']            
        except:
            return None
        return User.query.get(user_id)
    
    def __repr__(self):
        return f"User('{self.fullname}', '{self.username}', '{self.email}')"

class Leisure_journal(db.Model):
    leisure_id = db.Column(db.Integer, primary_key=True)
    activity = db.Column(db.String(50))
    description = db.Column(db.Text) 
    made_for=db.Column(db.String(10))
    duration=db.Column(db.Float,unique=False, nullable=False)
    made_on = db.Column(db.DateTime, nullable=False, default=datetime.utcnow())

    # Foreign Key To Link Users (refer to primary key of the user)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from application.config import Config
from flask_mail import Mail

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'user.login'
login_manager.login_message_category = 'info'
mail=Mail()


#app config settings
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from application.user.routes import user
    from application.main.routes import main    
    app.register_blueprint(user)
    app.register_blueprint(main)

    return app

application/main/routes.py
from flask import Blueprint,render_template

import json


#app config settings
main = Blueprint('main', __name__)




#app routes
@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html',title='Home')

@main.route('/about')
def about():
    return render_template('about.html',title='About')

application/user/routes.py
from flask import Blueprint, render_template,redirect,url_for,flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, current_user, logout_user, login_required
from application import db
from application.models import User
from application.user.wforms import SignupForm, LoginForm,RequestResetPwdForm,ResetPasswordForm
from application.user.utils import send_reset_email
#import json


#user blueprint initialization
user = Blueprint('user', __name__)


#user routes
@user.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
       
        check_user_email_in_db = User.query.filter_by(email=form.email.data).first()
        if check_user_email_in_db :
            flash(f'Please enter different email as {form.email.data} is already taken', 'danger')
            return redirect(url_for('signup'))
        
        check_user_username_in_db = User.query.filter_by(username=form.username.data).first()
        if check_user_username_in_db :
            flash(f'Please enter different username as {form.username.data} is already taken', 'danger')
            return redirect(url_for('user.signup'))
        
        hashed_pwd=generate_password_hash(form.password.data)
        user_created=User(fullname=form.fullname.data,
                          username=form.username.data,
                          dob=form.dob.data,
                          email=form.email.data,
                          password=hashed_pwd)
        db.session.add(user_created)
        db.session.commit()

        new_username=form.fullname.data
        # clear form

        flash(f'Account created for {new_username}!!! Please enter email and password to login', 'success')
        return redirect(url_for('user.login'))
    return render_template('signup.html',form=form)


@user.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('main.home'))            
            else:
                flash('Login Unsuccessful. Please check the password entered', 'danger')            
        else:
            flash('Login Unsuccessful. Please check email entered', 'danger')
    return render_template('login.html', title='Login', form=form)


@user.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
	logout_user()
	flash("You Have Been Logged Out!  Thanks For Stopping By...",'info')
	return redirect(url_for('user.login'))



@user.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    form = RequestResetPwdForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash(f'here is no account with that email. Please sign up first.', 'danger')
            return redirect(url_for('user.signup'))
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('user.login'))
    return render_template('reset_request.html', form=form)


@user.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pwd=generate_password_hash(form.password.data)        
        user.password = hashed_pwd
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('user.login'))
    return render_template('reset_passwd.html',  form=form)

application/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1> About page </h1>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>Apllication Demo - {{ title }}</title>
    {% else %}
        <title>Apllication Demo</title>
    {% endif %}
    
    <!-- Bootstrap stlye link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- local css link-->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

  </head>
  <body>
    <!-- Navbar-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.about')}}">About</a>
              </li>  
            </ul>
            <div class="navbar-nav-right" style= "margin-left:auto">
              <ul class="navbar-nav" > 
                  {% if current_user.is_authenticated %}           
                  <li class="nav-item" >
                    <a class="nav-link"  href="{{ url_for('user.logout')}}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item" >
                    <a class="nav-link"  href="{{ url_for('user.signup')}}">Signup</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('user.login')}}">Login</a>
                  </li>
                  {% endif %}       
            </ul>
          </div>
                 
          </div>
        </div>
      </nav>
    <div>
      {% block content %}
      {% endblock %}
      </br>
    </div>
    <!-- Flash messages-->
      </br>
      <div class="col-md-8" style="align-items: center;">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" style="margin-right: -500px;  text-align: center;">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>

    <!-- Bootstrap javascripts-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

application/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1> Home page </h1>
{% endblock %}

application/templates/login.html
{% extends 'base.html' %}
{% block content %}
</br>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="text-align: center;">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
        </br>
        </fieldset>
        <table>
            <tr>
                <td><small class="text-muted ml-2">
                    <a href="{{ url_for('user.reset_request') }}">Forgot Password?</a>
                </small></td>
                <td></td>
                <td> <div class="form-group" style="margin-left: 280px;">
                    {{ form.submit(class="btn btn-primary") }}
                </div></td>                
            </tr>           
       
         </table>
        </form>
       
    
    
    <div class="a1">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.signup') }}">Sign Up Now</a>
        </small>
    </div>
</div>

{% endblock %}

application/templates/reset_passwd.html
{% extends 'base.html' %}
{% block content %}
</br>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="text-align: center;">Reset Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
         
        </br>
        </fieldset>   
                 <div class="form-group" style="margin-left: 280px;">
                    {{ form.submit(class="btn btn-primary") }}
                </div>               
        </form>
</div>

{% endblock %}

application/templates/reset_request.html
{% extends 'base.html' %}
{% block content %}
</br>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="text-align: center;">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
     
         
        </br>
        </fieldset>   
                 <div class="form-group" style="margin-left: 280px;">
                    {{ form.submit(class="btn btn-primary") }}
                </div>               
        </form>
</div>

{% endblock %}

application/templates/signup.html
{% extends "base.html" %}
{% block content %}
</br>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4" style="text-align: center;">Create Account</legend>
                <div class="form-group">
                    {{ form.fullname.label(class="form-control-label") }}

                    {% if form.fullname.errors %}
                        {{ form.fullname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fullname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fullname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                  {{ form.dob.label(class="form-control-label") }}

                  {% if form.dob.errors %}
                      {{ form.dob(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.dob.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.dob(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
        </br>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
            <div class="a">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
                </small>
            </div>
        </form>
    </div>
   
{% endblock content %}